export const regionSelect : string[] = [
    "Aba North, Abia",
    "Aba South, Abia",
    "Umuahia North, Abia",
    "Umuahia South, Abia",
    "Isiala Ngwa North, Abia",
    "Yola North, Adamawa",
    "Yola South, Adamawa",
    "Mubi North, Adamawa",
    "Mubi South, Adamawa",
    "Ganye, Adamawa",
    "Uyo, Akwa Ibom",
    "Ikot Ekpene, Akwa Ibom",
    "Eket, Akwa Ibom",
    "Oron, Akwa Ibom",
    "Etinan, Akwa Ibom",
    "Awka North, Anambra",
    "Awka South, Anambra",
    "Nnewi North, Anambra",
    "Onitsha North, Anambra",
    "Ihiala, Anambra",
    "Ikeja, Lagos",
    "Surulere, Lagos",
    "Alimosho, Lagos",
    "Lagos Island, Lagos",
    "Ikorodu, Lagos",
    "Port Harcourt, Rivers",
    "Obio/Akpor, Rivers",
    "Bonny, Rivers",
    "Eleme, Rivers",
    "Ikwerre, Rivers",
    "Kano Municipal, Kano",
    "Fagge, Kano",
    "Nassarawa, Kano",
    "Gwale, Kano",
    "Dala, Kano",
    "Ibadan North, Oyo",
    "Ibadan South-West, Oyo",
    "Ogbomosho North, Oyo",
    "Iseyin, Oyo",
    "Oyo West, Oyo",
    "Kaduna North, Kaduna",
    "Kaduna South, Kaduna",
    "Zaria, Kaduna",
    "Kachia, Kaduna",
    "Jema’a, Kaduna",
    "Abuja Municipal, FCT",
    "Bwari, FCT",
    "Gwagwalada, FCT",
    "Kuje, FCT",
    "Kwali, FCT"
  ]

export const issueSelect : string[] = [
    "Roads & Infrastructure",
    "Electricity & Power",
    "Water & Sanitation",
    "Education",
    "Health Services",
    "Environment & Waste Management",
    "Jobs & Youth Empowerment",
    "Taxes & Levies",
    "Governance & Representation",
    "Housing & Urban Planning",
    "Markets & Small Business",
    "Elections & Voting Issues",
    "Social Services",
    "Public Safety & Security"
  ];

export const departments: string[] = [
    "Department of Agricultural Land Resources",
    "Department of Farm Input Support Services",
    "Department of Extension Services",
    "Department of Air Transport Management",
    "Department of Safety and Technical Policy",
    "Department of Postal Services",
    "Department of Information and Communications Technology",
    "Department of Army Affairs",
    "Department of Navy Affairs",
    "Department of Air Force Affairs",
    "Department of Basic and Secondary Education",
    "Department of Tertiary Education",
    "Department of Educational Planning",
    "Department of Climate Change",
    "Department of Pollution Control and Environmental Health",
    "Department of Finance",
    "Department of Budget and Planning",
    "Department of Revenue Mobilization",
    "Department of Regions (Africa, Europe, Americas, Asia/Pacific)",
    "Department of Consular and Immigration Services",
    "Department of Public Health",
    "Department of Hospital Services",
    "Department of Food and Drug Services",
    "Department of Information and Publications",
    "Department of Cultural Industries and Heritage",
    "Department of Citizenship and Business",
    "Nigeria Security and Civil Defence Corps",
    "Department of Public Prosecutions",
    "Department of Civil Litigation",
    "Department of Employment and Wages",
    "Department of Occupational Safety and Health",
    "Department of Mines",
    "Department of Steel",
    "Department of Petroleum Resources",
    "Department of Gas Resources",
    "Department of Electric Power",
    "Department of Renewable Energy",
    "Department of Scientific Research and Development",
    "Department of Technology Acquisition and Adoption",
    "Department of Road Transport",
    "Department of Rail Transport",
    "Department of Maritime Transport",
    "Department of Dams and Reservoir Operations",
    "Department of Water Supply and Quality Control",
    "Department of Highways Construction and Rehabilitation",
    "Department of Housing Development"
  ];